### ISSUE TITLE
decreaseIndentPattern fails on some common patterns

### ISSUE THREAD

**Issue by wyozi** [Lixquid/language-gmod-lua#1]
In my code I often use code like

``` lua
func():then_(function()
  return func2()
end):then_(function()

end)
```

or

``` lua
local t = {
  a = function()
  end,
  b = function()
  end,
}
```

which break on indentation, because the `end` keyword is not the only thing on the line.

Also code like

``` lua
if a then
elseif b then
end
```

breaks (elseif's indentation is higher than if's)

I think it would be better to check that the line starts with `( elseif | else | end | \\} )`, but a line should not need to end with it.

**Comment by Lixquid** [comment]
This should be fixed in 35e15c83fa2e9255e9437ec17d07afbc1cb3bb13.
