### ISSUE TITLE
not/and/or are not highlighted? ...

### ISSUE THREAD

**Issue by OmegaExtern** [Lixquid/language-gmod-lua#4]
![Image of this issue](http://i.imgur.com/YzAhKbK.png)

**Comment by Lixquid** [comment]
If I'm not mistaken, that looks like One Dark Syntax.

One Dark does not have rules defined for operators. The operators `+`, `-`, `*`, etc. should also be uncoloured.

Here's the same snippet with my theme, Deep Syntax, which has generic operator colouring:

![](http://i.imgur.com/X9H0810.png)
