### ISSUE TITLE
AtomLinter API deprecation

### ISSUE THREAD

**Issue by Partixel** [Lixquid/language-gmod-lua#6]
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
Report Issue
Object.activate - C:\Users\Nick.atom\packages\linter\lib\main.coffee:57:8
Package.activateNow - C:\Users\Nick\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:240:19
<unknown> - C:\Users\Nick\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:221:30
Package.measure - C:\Users\Nick\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:165:15
Package.activate - C:\Users\Nick\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package.js:213:14
PackageManager.activatePackage - C:\Users\Nick\AppData\Local\atom\app-1.0.2\resources\app.asar\src\package-manager.js:452:21
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
Report Issue
LinterLua.Linter - C:\Users\Nick.atom\packages\linter\lib\linter.coffee:60:4
new LinterLua - C:\Users\Nick.atom\packages\linter-glua\lib\linter-glua.coffee:21:4
Object.lint - C:\Users\Nick.atom\packages\linter\lib\legacy.coffee:61:21
<unknown> - C:\Users\Nick.atom\packages\linter\lib\editor-linter.coffee:69:25
currentLinter - C:\Users\Nick.atom\packages\linter\lib\editor-linter.coffee:68:19
<unknown> - C:\Users\Nick.atom\packages\linter\lib\editor-linter.coffee:82:22

**Comment by Lixquid** [comment]
Sorry, but this is the wrong repo. You need to report this on [the linter package](https://github.com/xaviergmail/linter-glua) instead.

**Comment by Partixel** [comment]
But your package is using deprecated linter APIs?

**Comment by Partixel** [comment]
https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
^

**Comment by Lixquid** [comment]
Perhaps I was unclear: My package purely provides the grammar. it has no interaction with the linter package in any way. Looking at that stacktrace, it looks like the [linter-glua](https://github.com/xaviergmail/linter-glua) package is using those deprecated APIs; you should report it there.

**Comment by Partixel** [comment]
Oh crap, I thought this was that package, my mistake sorry!
