### ISSUE TITLE
Coloring stops

### ISSUE THREAD

**Issue by MatsumotoYamaguchi** [Lixquid/language-gmod-lua#7]
![Image of Coloring stopping1](https://app.box.com/representation/file_version_40333609362/image_2048/1.png?shared_name=okqxpnp24uqsohrzrab2t512j6bqx836)

![Image of Coloring stopping2](http://i.imgur.com/OaGbssA.png)

**Comment by Lixquid** [comment]
I'm afraid this is a limitation in Atom itself; it cannot handle excessively large lines / excessively nested rules. Here's an example shot with the JavaScript grammar:

![js](http://i.imgur.com/lADIGkF.png)

I'm afraid there's not really much we can do except wait for grammar parsing to get more stable.
